### ISSUE TITLE
ModuleNotFoundError: No module named 'serializers_'

### ISSUE THREAD

**Issue by FromNetToDev** [renatoalmeidaoliveira/nbservice#16]
Hello, When I install this plugin to netbox (4.1.0) I got this error
`(venv) root@netbox:/opt/netbox/netbox# python3 /opt/netbox/netbox/manage.py migrate
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 519, in check
    for pattern in self.url_patterns:
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox-4.1.0/netbox/netbox/urls.py", line 12, in <module>
    from netbox.plugins.urls import plugin_patterns, plugin_api_patterns
  File "/opt/netbox-4.1.0/netbox/netbox/plugins/urls.py", line 35, in <module>
    urlpatterns = import_string(f"{plugin_path}.api.urls.urlpatterns")
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/nb_service/api/urls.py", line 2, in <module>
    from . import views
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/nb_service/api/views.py", line 5, in <module>
    from . import serializers
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/nb_service/api/serializers.py", line 9, in <module>
    from tenancy.api.nested_serializers import NestedTenantSerializer
  File "/opt/netbox-4.1.0/netbox/tenancy/api/nested_serializers.py", line 4, in <module>
    from serializers_.nested import NestedContactGroupSerializer, NestedTenantGroupSerializer
ModuleNotFoundError: No module named 'serializers_'`

**Comment by renatoalmeidaoliveira** [comment]
@FromNetToDev  fixed, please update the plugin, to v3.0.1 for NetBox  4.0.x, or v4.0.0 for NetBox v4.1.x
